version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: gigapress/mcp-server:latest
    container_name: mcp-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DYNAMIC_UPDATE_ENGINE_BASE_URL=http://dynamic-update-engine:8081
    depends_on:
      - redis
      - kafka
    networks:
      - gigapress-network
    restart: unless-stopped

# Reference external services from main docker-compose
networks:
  gigapress-network:
    external: true
